# Generated by Django 6.0.2 on 2026-03-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_leaverequest_workfromhomerequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='reason_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
